# Generated by Django 4.2.3 on 2023-07-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('level', models.IntegerField()),
                ('deadline', models.DateField()),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderTestPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ordertestinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('a', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=200)),
                ('c', models.CharField(max_length=200)),
                ('d', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='education.testcategory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTestPackStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('order_test_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ordertestpack')),
            ],
        ),
        migrations.AddField(
            model_name='ordertestpack',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.test'),
        ),
        migrations.CreateModel(
            name='OrderTestInfoStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ordertestinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentprofile')),
            ],
        ),
    ]
