# Generated by Django 4.2.3 on 2023-07-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile'),
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='education.testcategory'),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile'),
        ),
        migrations.AddField(
            model_name='ordertestpackstudent',
            name='order_test_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ordertestpack'),
        ),
        migrations.AddField(
            model_name='ordertestpackstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile'),
        ),
        migrations.AddField(
            model_name='ordertestpack',
            name='order_test_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ordertestinfo'),
        ),
        migrations.AddField(
            model_name='ordertestpack',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile'),
        ),
        migrations.AddField(
            model_name='ordertestpack',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.test'),
        ),
        migrations.AddField(
            model_name='ordertestinfostudent',
            name='order_test_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ordertestinfo'),
        ),
        migrations.AddField(
            model_name='ordertestinfostudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentprofile'),
        ),
        migrations.AddField(
            model_name='ordertestinfostudent',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile'),
        ),
        migrations.AddField(
            model_name='ordertestinfo',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile'),
        ),
    ]
