# Generated by Django 4.2.3 on 2023-07-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertestpackstudent',
            name='smth',
        ),
    ]
