# Generated by Django 4.2.3 on 2023-07-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_ordertestpackstudent_smth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertestpackstudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.ordertestinfostudent'),
        ),
    ]
