# Generated by Django 4.2.3 on 2023-07-24 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_ordertestpack_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertestinfostudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
