# Generated by Django 4.2.3 on 2023-07-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_studentprofile_verification_for_bot'),
        ('education', '0006_ordertestinfostudent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcategory',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.teacherprofile'),
        ),
    ]
