# Generated by Django 4.2.3 on 2023-07-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_telegram_id_studentprofile_parent_telegram_id'),
        ('education', '0007_alter_testcategory_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderTestInfoStudent',
            new_name='OrderTestInfoAssignStudent',
        ),
        migrations.RenameModel(
            old_name='OrderTestPackStudent',
            new_name='OrderTestPackResultsOfStudent',
        ),
    ]
