# Generated by Django 4.2.3 on 2023-07-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_rename_ordertestinfostudent_ordertestinfoassignstudent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertestpackresultsofstudent',
            name='order_test_pack',
        ),
        migrations.AddField(
            model_name='ordertestpackresultsofstudent',
            name='order_test_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.ordertestinfo'),
        ),
    ]
