# Generated by Django 4.2.3 on 2023-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_ordertestpackresultsofstudent_order_test_pack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertestinfo',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='ordertestinfo',
            name='to_id',
        ),
        migrations.AddField(
            model_name='ordertestinfo',
            name='categories',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
