# Generated by Django 4.2.3 on 2023-07-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usertraffic_facebook_alter_usertraffic_friend_and_more'),
        ('education', '0010_remove_ordertestinfo_from_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertestinfoassignstudent',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.testcategory'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacherprofile'),
        ),
    ]
