# Generated by Django 4.2.3 on 2023-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_ordertestinfoassignstudent_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertestinfo',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordertestinfo',
            name='status',
            field=models.CharField(choices=[('WHITE', 'white'), ('GREEN', 'green'), ('YELLOW', 'yellow')], default='WHITE', max_length=10),
        ),
    ]
