# Generated by Django 4.2.3 on 2023-07-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_group_date_group_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='source',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TELEGRAM', 'Telegram'), ('FRIEND', 'Friend'), ('LEAFLET', 'Leaflet'), ('OTHER', 'Other')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
