# Generated by Django 4.2.3 on 2023-07-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_studentprofile_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='verification_for_bot',
            field=models.BooleanField(default=False),
        ),
    ]
