# Generated by Django 4.2.2 on 2023-06-26 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_teacher_alter_studentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='must be in this format: +998999999999 ', regex='^\\+?1?\\d{9,13}$')]),
        ),
    ]
