# Generated by Django 4.2.3 on 2023-07-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_studentprofile_verification_for_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='telegram_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
