# Generated by Django 4.2.3 on 2023-07-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userincome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIncome',
            new_name='UserTraffic',
        ),
    ]
