# Generated by Django 4.2.3 on 2023-08-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
